name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        
      - name: GitHub Action
        uses: wearerequired/lint-action@v1
        
      - name: Checking (Only files changed in the PR)
        uses: wearerequired/lint-action@v1
        env:
          DIFF_BASE: ${{ github.base_ref }}
